workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  openapi-with-code-samples:
    inputs:
      - location: registry.speakeasyapi.dev/novu/novu/json-development:main
        # - location: https://api.novu.co/openapi.json
    overlays:
      - location: registry.speakeasyapi.dev/novu/novu/code-samples-typescript:main
      - fallbackCodeSamplesLanguage: python
      - fallbackCodeSamplesLanguage: java
      - fallbackCodeSamplesLanguage: go
    output: ./openapi.yaml
    registry:
      location: registry.speakeasyapi.dev/novu/novu/openapi-with-code-samples
targets: {}
